# Generated by Django 3.0.5 on 2020-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200416_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_status',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
