# Generated by Django 3.0.5 on 2020-04-16 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_company_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
